config/routes.rb
# coding: utf-8
AuricaCurkan::Application.routes.draw do
  root :to => 'main#index'

  devise_for :users

    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

    resources :contacts
    resources :events

    # delete '/logout' => 'sessions#destroy', :as => :logout
    # get '/login' => 'sessions#new', :as => :login
    # post '/register' => 'users#create', :as => :register
    # get '/signup' => 'users#new', :as => :signup
    #resources :users
    # resource :session
    get '/foto' => 'fotos#index', :as => :foto_index
    get '/video' => 'videos#index', :as => :video_index
    get '/about' => 'main#about', :as => :about_index
    get '/schedule' => 'main#schedule', :as => :schedule
    get '/payment' => 'main#payment', :as => :payment
    get '/camp_scheld' => 'main#camp_scheld', :as => :camp_scheld
    get '/help' => 'main#help', :as => :help
    get '/dance' => 'main#about_dance', :as => :about_dance_index
    get '/payment_order' => 'main#payment_order', :as => :payment_order
    resources :videos
    resources :publications
    resources :foto_albums
    resources :collectives
    resources :fotos do
      collection do
        post :swfupload
      end


    end

    resources :foto_albums
    resources :news
  # match '/:controller(/:action(/:id))'
end

app/models/video.rb
# coding: utf-8
class Video < ActiveRecord::Base
end

app/controllers/videos_controller.rb
# coding: utf-8
class VideosController < ApplicationController
  def access_denied
    redirect_to root_path
  end
    
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb

    end
  end

  # GET /videos/1
  # GET /videos/1.xml
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.xml
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.xml
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        flash[:notice] = 'Video was successfully created.'
        format.html { redirect_to(@video) }
        format.xml  { render :xml => @video, :status => :created, :location => @video }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.xml
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        flash[:notice] = 'Video was successfully updated.'
        format.html { redirect_to(@video) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.xml
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to(videos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/video_helper.rb
# coding: utf-8
module VideoHelper
end

app/helpers/videos_helper.rb
# coding: utf-8
module VideosHelper
end

app/views/videos/edit.html.erb
<% title "Редактирование видео" %>

<% form_for(@video) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<% title "Список видео" %>
<div class="media_content">
  <div class="media_item_video">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/JJuHFnGOWuk" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/aJehOYPBBqM" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/6b_t4EIuNYs" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/vvt_q3ObUsE" frameborder="0" allowfullscreen></iframe>
  </div>



  <div class="media_item_video">
    <iframe width="560" height="315" src="//www.youtube.com/embed/QEY1gg9qG5k" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="560" height="315" src="//www.youtube.com/embed/hIcXJCzUR-8" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="560" height="315" src="//www.youtube.com/embed/4SSNZt08IWY" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="560" height="315" src="//www.youtube.com/embed/BJG9o6nqYmA" frameborder="0" allowfullscreen></iframe>
  </div>


  <div class="media_item_video">
    <iframe width="420" height="315" src="http://www.youtube.com/embed/hNDoCqX_Vfs" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="420" height="315" src="http://www.youtube.com/embed/RB7i2D6Zjb0" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="420" height="315" src="http://www.youtube.com/embed/Dcy1tEkYDYA" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="420" height="315" src="http://www.youtube.com/embed/YdqKhHENzbo" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="420" height="315" src="http://www.youtube.com/embed/gUL9_spzug4" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="420" height="315" src="http://www.youtube.com/embed/bBFS4Wax08Y" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="media_item_video">
    <iframe width="420" height="315" src="http://www.youtube.com/embed/-0QQqx4tX4w" frameborder="0" allowfullscreen></iframe>
  </div>

  <div class="media_item_video">

    <OBJECT width="470" height="353">
      <PARAM name="movie" value="http://video.rutube.ru/a33b564a5cfffbcbb57e48554767d705"></PARAM>
      <PARAM name="wmode" value="window"></PARAM>
      <PARAM name="allowFullScreen" value="true"></PARAM>
      <EMBED src="http://video.rutube.ru/a33b564a5cfffbcbb57e48554767d705"
             type="application/x-shockwave-flash"
             wmode="window"
             width="470"
             height="353"
             allowFullScreen="true" >

      </EMBED>
    </OBJECT>

  </div>
</div>
<br/>
<%# if logged_in? -%>
    <%#= link_to 'New video', new_video_path %>
<%# end %>

app/views/videos/new.html.erb
<% title "Новое видео" %>

<% form_for(@video) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<% title "Просмотр видео" %>
<p>
  <b>Title:</b>
  <%=h @video.title %>
</p>

<p>
  <b>Description:</b>
  <%=h @video.description %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>