config/routes.rb
# coding: utf-8
AuricaCurkan::Application.routes.draw do
  root :to => 'main#index'

  devise_for :users

    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

    resources :contacts
    resources :events

    # delete '/logout' => 'sessions#destroy', :as => :logout
    # get '/login' => 'sessions#new', :as => :login
    # post '/register' => 'users#create', :as => :register
    # get '/signup' => 'users#new', :as => :signup
    #resources :users
    # resource :session
    get '/foto' => 'fotos#index', :as => :foto_index
    get '/video' => 'videos#index', :as => :video_index
    get '/about' => 'main#about', :as => :about_index
    get '/schedule' => 'main#schedule', :as => :schedule
    get '/payment' => 'main#payment', :as => :payment
    get '/camp_scheld' => 'main#camp_scheld', :as => :camp_scheld
    get '/help' => 'main#help', :as => :help
    get '/dance' => 'main#about_dance', :as => :about_dance_index
    get '/payment_order' => 'main#payment_order', :as => :payment_order
    resources :videos
    resources :publications
    resources :foto_albums
    resources :collectives
    resources :fotos do
      collection do
        post :swfupload
      end


    end

    resources :foto_albums
    resources :news
  # match '/:controller(/:action(/:id))'
end

app/models/contact.rb
# coding: utf-8
class Contact < ActiveRecord::Base

  # rails_admin do
  #   label "Контакты"
  #   list do
  #     field :title
  #
  #     field :description do
  #       formatted_value do # used in form views
  #         value.to_s.html_safe
  #       end
  #
  #     end
  #     field :created_at
  #     field :updated_at
  #
  #   end
  #   edit do
  #     field :title
  #     field :description, :text do
  #       ckeditor true
  #     end
  #   end
  # end
end

app/controllers/contacts_controller.rb
# coding: utf-8
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.xml
  skip_before_filter :authenticate_user!

  def index
    @contacts = Contact.all.order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.xml
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.xml
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.xml
  def create
    @contact = Contact.new(params[:contact])
   @contact.save!
    SupportMailer.contact_confirmation(@contact).deliver
        flash[:notice] = 'Ваше приглашение отправленно!'
         redirect_to root_url 

  end

  # PUT /contacts/1
  # PUT /contacts/1.xml
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        flash[:notice] = 'Contact was successfully updated.'
        format.html { redirect_to(@contact) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.xml
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to(contacts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/contacts_helper.rb
# coding: utf-8
module ContactsHelper
end

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<% form_for(@contact) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table style="color:white;">
  <tr>
    <td>Контактные данные</td>
    <td>Описание</td>
    <td></td>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.title %></td>
    <td><%= contact.description %></td>
    <!--<td><%#= link_to 'Show', contact %></td>-->
    <!--<td><%#= link_to 'Edit', edit_contact_path(contact) %></td>-->
    <td><%= link_to 'Destroy', contact, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New contact', new_contact_path %>

app/views/contacts/new.html.erb
<% title "Заявка на услуги" %>

<% form_for(@contact) do |f| %>
  <%= f.error_messages %>

    <p style="color:white; margin-top:20px; margin-bottom:20px;">
      <h1>Сдесь вы можете пригласить Аурику на ваше торжество</h1>
    </p>

  <p style="color:white; margin-top:20px; margin-bottom:20px;">
    <%= f.label "Контактый телефон" %><br /><br />
    <%= f.text_field :title %>
  </p>
  <p style="color:white;">
    <%= f.text_area :description ,:class=>"ckae"%>
  </p>  <p>
    <%= f.submit 'Добавить приглашение' %>
  </p>
<% end %>
<%= link_to 'Вернуться', new_contact_path %>

app/views/contacts/show.html.erb
<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>