config/routes.rb
# coding: utf-8
AuricaCurkan::Application.routes.draw do
  root :to => 'main#index'

  devise_for :users

    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

    resources :contacts
    resources :events

    # delete '/logout' => 'sessions#destroy', :as => :logout
    # get '/login' => 'sessions#new', :as => :login
    # post '/register' => 'users#create', :as => :register
    # get '/signup' => 'users#new', :as => :signup
    #resources :users
    # resource :session
    get '/foto' => 'fotos#index', :as => :foto_index
    get '/video' => 'videos#index', :as => :video_index
    get '/about' => 'main#about', :as => :about_index
    get '/schedule' => 'main#schedule', :as => :schedule
    get '/payment' => 'main#payment', :as => :payment
    get '/camp_scheld' => 'main#camp_scheld', :as => :camp_scheld
    get '/help' => 'main#help', :as => :help
    get '/dance' => 'main#about_dance', :as => :about_dance_index
    get '/payment_order' => 'main#payment_order', :as => :payment_order
    resources :videos
    resources :publications
    resources :foto_albums
    resources :collectives
    resources :fotos do
      collection do
        post :swfupload
      end


    end

    resources :foto_albums
    resources :news
  # match '/:controller(/:action(/:id))'
end

app/models/foto.rb
# coding: utf-8
require 'mime/types'

class Foto < ActiveRecord::Base
  belongs_to :foto_album
  


  has_attached_file :foto,
  :styles => {
    :thumb => "x100>",
    :lage => "x600>",
    :preveiw => "x150>",
    :mini => "50x50>"
  },
  :url => "/system/assets/fotos/:id/:style/:basename.:extension",
  :path => ":rails_root/public/system/assets/fotos/:id/:style/:basename.:extension",
  :default_url => "/images/No_photo.jpg"

  validates_attachment_size :foto, :less_than => 15.megabytes
  validates_attachment_content_type :foto, :content_type => ['image/jpeg', 'image/png', 'image/jpg', 'image/gif']



  # rails_admin do
  #   label "Фотографии"
  #   list do
  #     field :title
  #
  #     field :description do
  #       formatted_value do # used in form views
  #         value.to_s.html_safe
  #       end
  #
  #     end
  #     field :foto
  #     field :created_at
  #     field :updated_at
  #
  #   end
  #   edit do
  #     field :title
  #     field :description, :text do
  #       ckeditor true
  #     end
  #     field :foto
  #   end
  # end

end

app/controllers/fotos_controller.rb
# coding: utf-8
class FotosController < ApplicationController


  def access_denied
    redirect_to root_path
  end
    
  self.allow_forgery_protection = false
  
  def index
    @fotos = Foto.all
    @foto_album = FotoAlbum.find(:first)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fotos }
    end
  end

  # GET /fotos/1
  # GET /fotos/1.xml
  def show
    @foto = Foto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @foto }
    end
  end

  # GET /fotos/new
  # GET /fotos/new.xml
  def new
    @foto = Foto.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @foto }
    end
  end

  # GET /fotos/1/edit
  def edit
    @foto = Foto.find(params[:id])
  end

  # POST /fotos
  # POST /fotos.xml
  def create_foto
    @foto_album = FotoAlbum.find_by_id(params[:foto_album_id])
    params[:foto][:foto_album_id] = params[:foto_album_id]
    #raise params.inspect
    Foto.create(params[:foto])
    @fotos = Foto.find(:all, :conditions => {:foto_album_id => params[:foto_album_id]})

    responds_to_parent do
      render :update do |page|
        page.insert_html :bottom, "mlt_elements", :partial => 'foto_albums/fotos', :object => @foto
        #page.visual_effect :highlight, "ma_el_#{@product.id}", :duration => 1
      end
    end
  end

  # PUT /fotos/1
  # PUT /fotos/1.xml
  def update
    @foto = Foto.find(params[:id])

    respond_to do |format|
      if @foto.update_attributes(params[:foto])
        flash[:notice] = 'Фотография успешно обновленна.'
        format.html { redirect_to(@foto) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @foto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.xml
  def destroy
    @foto = Foto.find(params[:id])
    @foto.destroy

    respond_to do |format|
      format.html { redirect_to(fotos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/fotos_helper.rb
# coding: utf-8
module FotosHelper
end

app/views/fotos/edit.html.erb
<% title "Редактирование фотографии" %>

<% form_for(@foto, :html => { :multipart => true }) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit 'Сохранить' %>
  </p>
<% end %>

<%= link_to 'Просмотр', @foto %> |
<%= link_to 'Назад', fotos_path %>

app/views/fotos/index.html.erb
<% title "Список фотографий" %>
<h1>Список фотографий</h1>
<table>
  <tr>
    <th>Название</th>
    <th></th>
  </tr>

<% @fotos.each do |foto| %>
  <tr>
    <td><%=h foto.title %></td>
    <td><%= image_tag foto.foto.url(:mini) %></td>
    <% if logged_in? -%>
    <td><%= link_to 'Показать', foto %></td>
    <td><%= link_to 'Редактировать', edit_foto_path(foto) %></td>
    <td><%= link_to 'Удалить', foto, :confirm => 'Вы уверенны что хотите удалить фотографию?', :method => :delete %></td>
    <% end %>
        </tr>
<% end %>
</table>

<br />




<%= link_to 'Добавить еще фотографию', new_foto_path %>

app/views/fotos/new.html.erb
<% title "Новая фотография" %>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/mootools/1.2.2/mootools.js"></script>
<script type="text/javascript" src="/javascripts/fancy/Swiff.Uploader.js"></script>
<script type="text/javascript" src="/javascripts/fancy/Fx.ProgressBar.js"></script>
<script type="text/javascript" src="http://github.com/mootools/mootools-more/raw/master/Source/Core/Lang.js"></script>
<script type="text/javascript" src="/javascripts/fancy/FancyUpload2.js"></script>

<script type="text/javascript">
    //<![CDATA[

    /**
     * FancyUpload Showcase
     *
     * @license        MIT License
     * @author        Harald Kirschner <mail [at] digitarald [dot] de>
     * @copyright    Authors
     */

    window.addEvent('domready', function() { // wait for the content

        // our uploader instance

        var up = new FancyUpload2($('demo-status'), $('demo-list'), { // options object
            // we console.log infos, remove that in production!!
            verbose: true,

            // url is read from the form, so you just have to change one place
            url: $('new_foto').action,

            // path to the SWF file
            path: '/javascripts/fancy/Swiff.Uploader.swf',

            // remove that line to select all files, or edit it, add more items
            typeFilter: {
                'Images (*.jpg, *.jpeg, *.gif, *.png)': '*.jpg; *.jpeg; *.gif; *.png'
            },

            // this is our browse button, *target* is overlayed with the Flash movie
            target: 'demo-browse',

            // graceful degradation, onLoad is only called if all went well with Flash
            onLoad: function() {
                $('demo-status').removeClass('hide'); // we show the actual UI
                $('demo-fallback').destroy(); // ... and hide the plain form

                // We relay the interactions with the overlayed flash to the link
                this.target.addEvents({
                    click: function() {
                        return false;
                    },
                    mouseenter: function() {
                        this.addClass('hover');
                    },
                    mouseleave: function() {
                        this.removeClass('hover');
                        this.blur();
                    },
                    mousedown: function() {
                        this.focus();
                    }
                });

                // Interactions for the 2 other buttons

                $('demo-clear').addEvent('click', function() {
                    up.remove(); // remove all files
                    return false;
                });

                $('demo-upload').addEvent('click', function() {
                    up.start(); // start upload
                    return false;
                });
            },

            // Edit the following lines, it is your custom event handling

            /**
             * Is called when files were not added, "files" is an array of invalid File classes.
             *
             * This example creates a list of error elements directly in the file list, which
             * hide on click.
             */
            onSelectFail: function(files) {
                files.each(function(file) {
                    new Element('li', {
                        'class': 'validation-error',
                        html: file.validationErrorMessage || file.validationError,
                        title: MooTools.lang.get('FancyUpload', 'removeTitle'),
                        events: {
                            click: function() {
                                this.destroy();
                            }
                        }
                    }).inject(this.list, 'top');
                }, this);
            },

            /**
             * This one was directly in FancyUpload2 before, the event makes it
             * easier for you, to add your own response handling (you probably want
             * to send something else than JSON or different items).
             */
            onFileSuccess: function(file, response) {
                var json = new Hash(JSON.decode(response, true) || {});

                if (json.get('status') == '1') {
                    file.element.addClass('file-success');
                    file.info.set('html', '<strong>Image was uploaded:</strong> ' + json.get('width') + ' x ' + json.get('height') + 'px, <em>' + json.get('mime') + '</em>)');
                } else {
                    file.element.addClass('file-failed');
                    file.info.set('html', '<strong>An error occured:</strong> ' + (json.get('error') ? (json.get('error') + ' #' + json.get('code')) : response));
                }
            },

            /**
             * onFail is called when the Flash movie got bashed by some browser plugin
             * like Adblock or Flashblock.
             */
            onFail: function(error) {
                switch (error) {
                    case 'hidden': // works after enabling the movie and clicking refresh
                        alert('To enable the embedded uploader, unblock it in your browser and refresh (see Adblock).');
                        break;
                    case 'blocked': // This no *full* fail, it works after the user clicks the button
                        alert('To enable the embedded uploader, enable the blocked Flash movie (see Flashblock).');
                        break;
                    case 'empty': // Oh oh, wrong path
                        alert('A required file was not found, please be patient and we fix this.');
                        break;
                    case 'flash': // no flash 9+ :(
                        alert('To enable the embedded uploader, install the latest Adobe Flash plugin.')
                }
            }

        });

    });
    //]]>
</script>

<% form_for(@foto, :html => { :multipart => true }) do |f| %>
    <%= f.error_messages %>

    <p>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_area :description %>
    </p>

    <p>
    <fieldset id="demo-fallback">
            <legend>File Upload</legend>
            <p>
                This form is just an example fallback for the unobtrusive behaviour of FancyUpload.
                If this part is not changed, something must be wrong with your code.
            </p>
            <label for="demo-photoupload">
                Upload a Photo:
               <%#= f.file_field :foto, :id => "upload" %>
                <input type="file" name="foto" />
            </label>
        </fieldset>
    
    <div id="demo-status" class="hide">
      <p>
        <a href="#" id="demo-browse">Browse Files</a> |
        <a href="#" id="demo-clear">Clear List</a> |
        <a href="#" id="demo-upload">Start Upload</a>
      </p>

      <div>
        <strong class="overall-title"></strong><br/>
        <img src="../../images/progress-bar/bar.gif" class="progress overall-progress"/>
      </div>
      <div>
        <strong class="current-title"></strong><br/>
        <img src="../../images/progress-bar/bar.gif" class="progress current-progress"/>
      </div>
      <div class="current-text"></div>
    </div>

    <ul id="demo-list"></ul>

    <%= f.submit 'Добавить', :class => 'upload' %>

<% end %>
<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<% title "Просмотр фото" %>
<h1>Фотография - <%=h @foto.title %></h1>
<p>
  <b>Название:</b>
  <%=h @foto.title %>
</p>

<p>
  <b></b>
  <% #raise @foto.foto.inspect  %>
  <%= image_tag @foto.foto.url(:thumb) %>
</p>

<% if logged_in? -%>
<%= link_to 'Редактировать', edit_foto_path(@foto) %> |
<%= link_to 'Вернуться к списку', fotos_path %>
<% end %>